### ISSUE TITLE
Decode  traceback (most recent call last)

### ISSUE THREAD

**Issue by zhengsw** [sanshirookazaki/chat#2]
When can i quit exit training?
I taining more than 10 times,like this:
global step 1500 learning rate 0.5000 step-time 0.12 perplexity 1.28
then i stop training .

When i do command : 
python translate.py --decode --data_dir datas --train_dir datas
and input "hello",
## Traceback (most recent call last)

[root@localhost chat]# python translate.py --decode --data_dir datas --train_dir datas
Hello!!
Reading model parameters from datas/translate.ckpt-1500

> hello
> Traceback (most recent call last):
>   File "translate.py", line 240, in <module>
>     tf.app.run()
>   File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
>     sys.exit(main(sys.argv))
>   File "translate.py", line 235, in main
>     decode()
>   File "translate.py", line 198, in decode
>     target_weights, bucket_id, True)
>   File "/usr/lib/python2.7/site-packages/tensorflow/models/rnn/translate/seq2seq_model.py", line 244, in step
>     outputs = session.run(output_feed, input_feed)
>   File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 710, in run
>     run_metadata_ptr)
>   File "/usr/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 887, in _run
>     % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
> ValueError: Cannot feed value of shape (1,) for Tensor u'decoder6:0', which has shape '(4,)'

---

Is't training error ?

**Comment by sanshirookazaki** [comment]
at the appropriate time, you can stop training.
your training may be right. 

according to error log , tensor shape is wrong.
this model deal with variable length data. 
so , this model makes use of Bucketing and padding.
"Bucketing and padding":[https://www.tensorflow.org/versions/r0.10/tutorials/seq2seq/index.html](url) 

Could you train sentence data of various length ?
